services:
  - type: web
    name: moodle
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MOODLE_DB_HOST
        fromService: moodle-db
        property: host
      - key: MOODLE_DB_PORT
        fromService: moodle-db
        property: port
      - key: MOODLE_DB_USER
        value: moodle_user
      - key: MOODLE_DB_PASSWORD
        value: moodle_pass
      - key: MOODLE_DB_NAME
        value: moodle_db
      - key: MOODLE_URL
        value: https://moodle.onrender.com

  - type: pserv
    name: moodle-db
    env: docker
    plan: free
    dockerImage: mariadb:10.6
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: moodle_db
      - key: MYSQL_USER
        value: moodle_user
      - key: MYSQL_PASSWORD
        value: moodle_pass
